# Generated by Django 6.0.4 on 2026-04-13 10:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non-binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('pronouns', models.CharField(blank=True, max_length=30)),
                ('college_name', models.CharField(blank=True, max_length=150)),
                ('stream', models.CharField(blank=True, choices=[('Computer Science', 'Computer Science'), ('Electronics & Communication', 'Electronics & Communication'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Information Technology', 'Information Technology'), ('Business Administration', 'Business Administration'), ('Economics', 'Economics'), ('Psychology', 'Psychology'), ('Law', 'Law'), ('Medicine', 'Medicine'), ('Architecture', 'Architecture'), ('Arts & Humanities', 'Arts & Humanities'), ('Science', 'Science'), ('Commerce', 'Commerce'), ('Other', 'Other')], max_length=60)),
                ('year_of_study', models.IntegerField(blank=True, choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5'), (6, 'Year 6')], null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('region', models.CharField(choices=[('open', 'All India'), ('north', 'North India'), ('south', 'South India'), ('east', 'East India'), ('west', 'West India'), ('central', 'Central India'), ('northeast', 'Northeast India')], default='open', max_length=20)),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('icebreaker', models.TextField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('avatar_color', models.CharField(default='#D4537E', max_length=10)),
                ('avatar_initials', models.CharField(blank=True, max_length=3)),
                ('interests', models.TextField(blank=True, help_text='Comma-separated interests')),
                ('love_language', models.CharField(blank=True, choices=[('words', 'Words of affirmation'), ('acts', 'Acts of service'), ('gifts', 'Receiving gifts'), ('time', 'Quality time'), ('touch', 'Physical touch')], max_length=20)),
                ('humor_style', models.CharField(blank=True, choices=[('dry', 'Dry'), ('sarcastic', 'Sarcastic'), ('silly', 'Silly'), ('witty', 'Witty'), ('dark', 'Dark'), ('wholesome', 'Wholesome')], max_length=20)),
                ('communication_style', models.CharField(blank=True, choices=[('texter', 'Text person'), ('caller', 'Phone calls'), ('voice_notes', 'Voice notes'), ('all_good', "All's good")], max_length=20)),
                ('relationship_goal', models.CharField(blank=True, choices=[('serious', 'Serious relationship'), ('casual', 'Casual dating'), ('friendship', 'Friendship'), ('study_partner', 'Study partner'), ('see_what_happens', 'See what happens')], max_length=25)),
                ('preferred_gender', models.TextField(blank=True, help_text='Comma-separated genders')),
                ('preferred_region', models.CharField(default='open', max_length=20)),
                ('age_min', models.IntegerField(default=18)),
                ('age_max', models.IntegerField(default=30)),
                ('long_distance_ready', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('profile_complete', models.BooleanField(default=False)),
                ('setup_step', models.IntegerField(default=0)),
                ('is_banned', models.BooleanField(default=False)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('daily_prompt_streak', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'accounts_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
